sonar.projectKey=SFWRENG-2AA4-Team-21_2AA4-Assignment-3
sonar.organization=sfwreng-2aa4-team-21

sonar.sources=src
sonar.tests=test

sonar.java.binaries=.sonar.projectKey=ANANYASHARMA3064_a2repo2AA4
sonar.organization=ananyasharma3064

sonar.sources=src
sonar.java.binaries=.
sonar.sourceEncoding=UTF-8
sonar.coverage.jacoco.xmlReportPaths=coverage/jacoco.xml
